name: Push Event Workflow

on:
  push:
    branches:
      - development

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Install Packages
        run: pip install pytest

      - name: Run tests
        run: pytest tests/test_mathy_stuff.py

      - name: Merge development into main
        if: success()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin main:main          
          git checkout main
          git reset --hard origin/main
          git merge development --no-commit --no-ff --allow-unrelated-histories -m "Merging into main"
          git push origin main
