name: Push Event Workflow

on:
  push:
    branches:
      - "main"
      - "development" #working on the development branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: pip install pytest

      - name: Run tests
        run: pytest tests/test_mathy_stuff.py

      - name: Push to main
        if: success()
        run: |
          git config --global user.name 'Greg Ryslik'
          git config --global user.email 'gryslik@gmail.com'
          git checkout main
          git merge development
          git push origin main
